/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import logica.estatura;

/**
 *
 * @author angel
 */
public class Pantallaestatura extends javax.swing.JFrame {

    /**
     * Creates new form Pantallaestatura
     */
    private double[] estaturas;
     private int numEstaturas =0;
     private int contador =0;
     
    public Pantallaestatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla = new javax.swing.JPanel();
        resultado = new javax.swing.JLabel();
        mensaje2 = new javax.swing.JLabel();
        ingresodatos = new javax.swing.JTextField();
        mensaje1 = new javax.swing.JLabel();
        numerodedatos = new javax.swing.JTextField();
        aceptardatos = new javax.swing.JButton();
        calculo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pantalla.setBorder(new javax.swing.border.MatteBorder(null));
        pantalla.setForeground(new java.awt.Color(255, 255, 0));

        mensaje2.setText("Ingrese el total de estaturas");

        ingresodatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresodatosActionPerformed(evt);
            }
        });

        mensaje1.setText("Cuantas estaturas desea ingresar");

        aceptardatos.setText("Aceptar");
        aceptardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptardatosActionPerformed(evt);
            }
        });

        calculo.setText("Calcular");
        calculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pantallaLayout = new javax.swing.GroupLayout(pantalla);
        pantalla.setLayout(pantallaLayout);
        pantallaLayout.setHorizontalGroup(
            pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pantallaLayout.createSequentialGroup()
                        .addComponent(mensaje2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ingresodatos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(pantallaLayout.createSequentialGroup()
                        .addGroup(pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pantallaLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(mensaje1)))
                        .addGroup(pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pantallaLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(numerodedatos, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(aceptardatos)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantallaLayout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(calculo)
                                .addGap(53, 53, 53))))))
        );
        pantallaLayout.setVerticalGroup(
            pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mensaje1)
                    .addComponent(numerodedatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aceptardatos))
                .addGroup(pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pantallaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(pantallaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mensaje2)
                            .addComponent(ingresodatos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(calculo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptardatosActionPerformed
        // TODO add your handling code here:
         String x = numerodedatos.getText();
          numEstaturas = Integer.parseInt(x);
          estaturas =new double[numEstaturas];
         
         mensaje2.setText("ingrese la estatura 1 de "+numEstaturas);

    }//GEN-LAST:event_aceptardatosActionPerformed

    private void calculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculoActionPerformed
        // TODO add your handling code here:
       
        
         // Obtener los datos ingresados en el JTextField
         
    
    // se crea objeto y constructor y se llama un set
    estatura calculadora = new estatura(estaturas);
    calculadora.setEstMy();
    calculadora.setEstMn();
    
    // se llaman los getters
    double mayor = calculadora.getEstMy();
    double menor = calculadora.getEstMn();
    
    //aqui da el resultado de estatura alta y estatura baja
   
    resultado.setText("<html>Estatura mayor: " + mayor + "<br>Estatura menor: " + menor + "</html>");
    
    }//GEN-LAST:event_calculoActionPerformed

    private void ingresodatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresodatosActionPerformed
        // TODO add your handling code here:
        if (contador < numEstaturas) {
            double estatura = Double.parseDouble(ingresodatos.getText());
            estaturas[contador] = estatura; 
            contador++;

            
            if (contador < numEstaturas) {
                mensaje2.setText("Ingrese la estatura " + (contador + 1) + " de " + numEstaturas);
    
            } else {
                mensaje2.setText("Todas las estaturas han sido ingresadas, presione calcular.");
            }
            ingresodatos.setText(""); 
        }
    }//GEN-LAST:event_ingresodatosActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptardatos;
    private javax.swing.JButton calculo;
    private javax.swing.JTextField ingresodatos;
    private javax.swing.JLabel mensaje1;
    private javax.swing.JLabel mensaje2;
    private javax.swing.JTextField numerodedatos;
    private javax.swing.JPanel pantalla;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
